export interface MatchModel {
  id: number,
  createdAt: Date,
  createdBy: number,
  updatedAt: Date,
  updatedBy: number,
  groupstageId: number,
  matchNo: string,
  matchWeek: number,
  matchDate: Date,
  matchStatus: string,
  stadiumId: number,
  homeTeamId: number,
  homeTeamScore: number,
  isHomeTeamWinByForfeit: boolean,
  homeTeamPoint: number,
  awayTeamId: number,
  awayTeamScore: number,
  isAwayTeamWinByForfeit: boolean,
  awayTeamPoint: number,
  explanation: string,
  orderNo: number,
}
