export const fontAwesomeList = [
  "fa-brands fa-facebook",
  "fa-brands fa-facebook-f",
  "fa-brands fa-square-facebook",
  "fa-brands fa-twitter",
  "fa-brands fa-square-twitter",
  "fa-brands fa-instagram",
  "fa-brands fa-square-instagram",
  "fa-brands fa-youtube",
  "fa-brands fa-square-youtube",
  "fa-brands fa-tiktok",
  "fa-brands fa-linkedin",
  "fa-brands fa-linkedin-in",
  "fa-brands fa-google-plus-g",
  "fa-brands fa-google-plus",
  "fa-brands fa-pinterest",
  "fa-brands fa-pinterest-p",
  "fa-brands fa-square-pinterest",
];
