export interface FixtureModel {
  id: number,
  groupstageId: number,
  matchNo: string,
  matchWeek: number,
  matchDate: Date,
  matchStatus: string,
  stadiumId: number,
  stadiumName: string,
  homeTeamId: number,
  homeTeamOfficialName: string,
  homeTeamShortName: string,
  homeTeamScore: number,
  isHomeTeamWinByForfeit: boolean,
  homeTeamPoint: number,
  awayTeamId: number,
  awayTeamOfficialName: string,
  awayTeamShortName: string,
  awayTeamScore: number,
  isAwayTeamWinByForfeit: boolean,
  awayTeamPoint: number,
  explanation: string,
  orderNo: number,
}
