export interface DisciplinaryBoardDecisionModel {
    id: number,
    disciplinaryBoardFileId: number,
    caseNo: string,
    leagueName: string,
    teamOfficialName: string,
    teamShortName: string,
    teamImagePath: string,
    fullName: string,
    licenseNo: string,
    belongingTo: string,
    penalType: string,
    duration: string,
    explanation: string,
}
